PortfolioManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('corperations/', include('corperations.urls')),
    path('', views.index, name='index')
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.signin, name='signin'),
    path('logout/', views.signout, name='signout'),
    path('password/', views.change_password, name='change_password')
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models

# Create your models here.

corperations/models.py
from django.db import models

# Create your models here.
class Corperation(models.Model):
    c_name = models.CharField(max_length=20)
    c_code = models.CharField(max_length=10, primary_key=True)
    c_price = models.IntegerField()
    sales_21 = models.IntegerField()
    operatingincome_21 = models.IntegerField()
    netincome_21 = models.IntegerField()
    sales_20 = models.IntegerField()
    operatingincome_20 = models.IntegerField()
    netincome_20 = models.IntegerField()
    market_cap = models.TextField()
    last_updated_date = models.DateField(default="2000-01-01")

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model


class CustomUser(UserCreationForm):
    pass

class CustomUserChangeForm(UserChangeForm):

    password = None
    
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name')

PortfolioManagement/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

accounts/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_safe, require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login, logout as auth_logout, update_session_auth_hash
from .forms import CustomUserChangeForm


@login_required
@require_http_methods(['GET','POST'])
# Create your views here.
def index(request):
    if request.method =="POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')
    else:
        form = CustomUserChangeForm(instance=request.user)

    context = {
        'form':form
    }
    return render(request, 'accounts/index.html', context)


@require_http_methods(['GET','POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('index')
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('index')
    else:
        form = UserCreationForm
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET','POST'])
def signin(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'index')
    else:
        form = AuthenticationForm
    context = {
        'form': form
    }
    return render(request, 'accounts/signin.html', context)


@login_required
def signout(request):
    if request.method == "POST":
        auth_logout(request)
    return redirect('index')


@login_required
@require_http_methods(['GET','POST'])
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)   
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


@login_required
def checktodelete(request):
    render(request, 'accounts/delete.html')


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect('accounts:index')

articles/views.py
from django.shortcuts import render

# Create your views here.

corperations/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/accounts/change_password.html
{% extends 'account_base.html' %}

{% block subtitle %}비밀번호 변경{% endblock subtitle %}

{% block detail %}
<form action="" method="POST">
  {% csrf_token %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><p class="fs-5 fw-bold my-1">비밀번호 관리</p></th>
      </tr>
    </thead>
    <tbody>
      {% for attr in form %}
        <tr>
          <th style='width:200px; line-height:2;'>{{ attr.label_tag }}</th>
          <th>{{ attr }}</th>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div "float-right py-3">
    <button class="btn btn-dark" type="submit">변경</button>
    <a href="{% url 'accounts:index' %}" class='btn text-decoration-underline'>취소</a>
  </div>
</form>
{% endblock detail %}

accounts/templates/accounts/delete.html
{% extends 'accounts_base.html' %}

{% block detail %}
<form action="{% url 'accounts:delete' %}" method="POST">
  정말 회원 탈퇴 하시겠습니까?
  <button class='btn btn-dark'>확인</button>
  <a href="{% url 'accounts:index' %}" class='btn'>취소</a>
</form>
{% endblock detail %}

accounts/templates/accounts/index.html
{% extends 'account_base.html' %}

{% block subtitle %}내 정보{% endblock subtitle %}

{% block detail %}
  <form action="" method="POST">
    {% csrf_token %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col"><p class="fs-5 fw-bold my-1">내 정보 관리</p></th>
        </tr>
      </thead>
      <tbody>
        {% for attr in form %}
          <tr>
            <th style='width:200px; line-height:2;' >{{ attr.label_tag }}</th>
            <th>{{ attr }}</th>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div "float-right py-3">
      <button type='submit' class='btn btn-dark'>수정</button>
      <button type='reset' class='btn text-decoration-underline'>취소</button>
    </div>
  </form>
{% endblock detail %}

accounts/templates/accounts/signin.html
{% extends 'base.html' %}

{% block content %}
<h2>로그인</h2>
<hr>
<table>
  <form action="" method="POST">
    {% csrf_token %}
    <table class="table">
      <tbody>
        {% for attr in form %}
          <tr>
            <th style='width:200px; line-height:2;' >{{ attr.label_tag }}</th>
            <th>{{ attr }}</th>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div "float-right py-3">
      <button class="btn btn-dark " type="submit">회원가입</button>
    </div>
  </form>
</table>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>회원 가입</h2>
  <hr>
  <table>
    <form action="" method="POST">
      {% csrf_token %}
      <table class="table">
        <tbody>
          {% for attr in form %}
            <tr>
              <th style='width:200px; line-height:2;' >{{ attr.label_tag }}</th>
              <th>{{ attr }}</th>
              {% if attr.errors %}
                <p class="text-danger">{{ attr.errors }}</p>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <div "float-right py-3">
        <button class="btn btn-dark " type="submit">회원가입</button>
      </div>
    </form>
  </table>

  {% comment %} <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}

  </form> {% endcomment %}
{% endblock content %}

templates/account_base.html
{% extends 'base.html' %}

{% block content %}
  <h2>{% block subtitle %}{% endblock subtitle %}</h2>
  <hr>
  <div class="row my-5">
    <div class="col-2">
      <table class="table">
        <thead>
          <tr>
            <th scope="col"><p class="fs-5 fw-bold my-1">내 정보 관리</p></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th><a href="{% url 'accounts:index' %}" class="btn m-0 p-0">개인정보 변경</a></th>
          </tr>
          <tr>
            <th><a href="{% url 'accounts:change_password' %}" class="btn m-0 p-0">비밀번호 변경</a></th>
          </tr>
          <tr>
            <th>
              <form action="" method="POST">
                {% csrf_token %}
                <button class="btn m-0 p-0">회원탈퇴</button>
              </form>
            </th>
        </tbody>
      </table>
    </div>
    <div class="col-9 mx-5">
      <div>
        {% block detail %}
        {% endblock detail %}
      </div>
    </div>
  </div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
  <div class="container">
    <header class="my-3 d-flex justify-content-between items-align-center">
      <div class="start" style="width:200px"></div>
      <div class="center"><a href="{% url 'index' %}" class="text-black text-decoration-none"><h1 class="fs-1 fw-bold text-center">Portfolio Management</h1></a></div>
      <div class="end my-auto row" style="width:200px">
        {% if request.user.is_authenticated %}
          <div class="col-6 my-auto">Hello, <a href="{% url 'accounts:index' %}">{{ user.username }}</a></div>
          <form action="{% url 'accounts:signout' %}" method="POST" class="px-0 mx-auto my-auto col-6 text-center">
            {% csrf_token %}
            <button class="btn text-black text-decoration-none">로그아웃</button>
          </form>
        {% else %}
          <div class="col-6 my-auto px-0"><a href="{% url 'accounts:signup' %}" class="btn text-black text-decoration-none">회원가입</a></div>
          <div class="col-6 my-auto"><a href="{% url 'accounts:signin' %}" class='btn text-black text-decoration-none'>로그인</a></div>
        {% endif %}
      </div>
    </header>
  </div>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark my-3">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse d-flex justify-content-center" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item mx-5">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">홈</a>
          </li>
          <li class="nav-item mx-5">
            <a class="nav-link active" href="#">종목 검색</a>
          </li>
          <li class="nav-item mx-5">
            <a class="nav-link active" href="#">종목 추가</a>
          </li>
          <li class="nav-item mx-5">
            <a class="nav-link active" href="#">포트폴리오 분석</a>
          </li>
          <li class="nav-item mx-5">
            <a class="nav-link active" href="#">MY 자산</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  
  <div class="container my-5">

    {% block content %}
      <p>default content</p>
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
기본페이지 
{% endblock content %}